#index:
#    path: /
#    controller: App\Controller\DefaultController::index

account_order:
  path: /compte/mes-commandes
  controller: App\Controller\AccountOrderController::index

account_order_show:
   path: /compte/mes-commandes/{reference}
   controller: App\Controller\AccountOrderController::show
